// Generated by: main
// TypeWriter: slice
// Directive: +gen on string

package comm

// StrSlice is a slice of type string. Use it where you would use []string.
type StrSlice []string

// All verifies that all elements of StrSlice return true for the passed func. See: http://clipperhouse.github.io/gen/#All
func (rcv StrSlice) All(fn func(string) bool) bool {
	for _, v := range rcv {
		if !fn(v) {
			return false
		}
	}
	return true
}
