// Generated by: main
// TypeWriter: set
// Directive: +gen on string

package comm

// Set is a modification of https://github.com/deckarep/golang-set
// The MIT License (MIT)
// Copyright (c) 2013 Ralph Caraveo (deckarep@gmail.com)

// The primary type that represents a set
type StrSet map[string]struct{}

// Creates and returns a reference to an empty set.
func NewStrSet(a ...string) StrSet {
	s := make(StrSet)
	for _, i := range a {
		s.Add(i)
	}
	return s
}

// ToSlice returns the elements of the current set as a slice
func (set StrSet) ToSlice() []string {
	var s []string
	for v := range set {
		s = append(s, v)
	}
	return s
}

// Adds an item to the current set if it doesn't already exist in the set.
func (set StrSet) Add(i string) bool {
	_, found := set[i]
	set[i] = struct{}{}
	return !found //False if it existed already
}

// Determines if a given item is already in the set.
func (set StrSet) Contains(i string) bool {
	_, found := set[i]
	return found
}

// Determines if the given items are all in the set
func (set StrSet) ContainsAll(i ...string) bool {
	for _, v := range i {
		if !set.Contains(v) {
			return false
		}
	}
	return true
}

// Determines if every item in the other set is in this set.
func (set StrSet) IsSubset(other StrSet) bool {
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Determines if every item of this set is in the other set.
func (set StrSet) IsSuperset(other StrSet) bool {
	return other.IsSubset(set)
}

// Returns a new set with all items in both sets.
func (set StrSet) Union(other StrSet) StrSet {
	unionedSet := NewStrSet()

	for elem := range set {
		unionedSet.Add(elem)
	}
	for elem := range other {
		unionedSet.Add(elem)
	}
	return unionedSet
}

// Returns a new set with items that exist only in both sets.
func (set StrSet) Intersect(other StrSet) StrSet {
	intersection := NewStrSet()
	// loop over smaller set
	if set.Cardinality() < other.Cardinality() {
		for elem := range set {
			if other.Contains(elem) {
				intersection.Add(elem)
			}
		}
	} else {
		for elem := range other {
			if set.Contains(elem) {
				intersection.Add(elem)
			}
		}
	}
	return intersection
}

// Returns a new set with items in the current set but not in the other set
func (set StrSet) Difference(other StrSet) StrSet {
	differencedSet := NewStrSet()
	for elem := range set {
		if !other.Contains(elem) {
			differencedSet.Add(elem)
		}
	}
	return differencedSet
}

// Returns a new set with items in the current set or the other set but not in both.
func (set StrSet) SymmetricDifference(other StrSet) StrSet {
	aDiff := set.Difference(other)
	bDiff := other.Difference(set)
	return aDiff.Union(bDiff)
}

// Clears the entire set to be the empty set.
func (set *StrSet) Clear() {
	*set = make(StrSet)
}

// Allows the removal of a single item in the set.
func (set StrSet) Remove(i string) {
	delete(set, i)
}

// Cardinality returns how many items are currently in the set.
func (set StrSet) Cardinality() int {
	return len(set)
}

// Iter() returns a channel of type string that you can range over.
func (set StrSet) Iter() <-chan string {
	ch := make(chan string)
	go func() {
		for elem := range set {
			ch <- elem
		}
		close(ch)
	}()

	return ch
}

// Equal determines if two sets are equal to each other.
// If they both are the same size and have the same items they are considered equal.
// Order of items is not relevent for sets to be equal.
func (set StrSet) Equal(other StrSet) bool {
	if set.Cardinality() != other.Cardinality() {
		return false
	}
	for elem := range set {
		if !other.Contains(elem) {
			return false
		}
	}
	return true
}

// Returns a clone of the set.
// Does NOT clone the underlying elements.
func (set StrSet) Clone() StrSet {
	clonedSet := NewStrSet()
	for elem := range set {
		clonedSet.Add(elem)
	}
	return clonedSet
}
